name = 'Vortisil'
license = 'GPL-3.0-or-later'
licenselink = 'https://github.com/khitezza/vortisil/LICENSE'
description = 'A fast, minimal and restrained Hugo theme...'
homepage = 'https://github.com/khitezza/vortisil'
demosite = "https://github.com/khitezza/vortisil"
tags = ["blog", "responsive", "clean", "light", "dark", "personal"]
features = ["blog", "darkmode", "responsive", "search"]
min_version = "0.142.0"

[author]
name = 'Hao Wu'
homepage = 'https://khitezza.com'
